#!/bin/sh
## ------------------------------------------------------------------------------
## need to copy data files for running into desired run folder
## -j oe combines output (o) and error (e) into one file (default behavior separates them)

#PBS -A XXX 
#PBS -N tpose_ad
#PBS -j oe
#PBS -q main
#PBS -l walltime=07:00:00
#PBS -l select=3:ncpus=128:mpiprocs=64

## load modules (compiler, MPI, etc.)
module --force  purge
module load ncarenv/23.09 intel/2023.2.1 intel-mpi/2021.10.0
module list

export TMPDIR=/glade/derecho/scratch/edavenport/temp && mkdir $TMPDIR

cd /glade/derecho/scratch/edavenport/assim/tpose/sep2012/run_ad/

## link necessary inputs 
#ln -s ../../constraints/* .
#ln -s ../../linked_files/* .
#ln -s /glade/work/edavenport/ERA5/ERA5* .
#ln -s ../../previous_state/* .

## copy data files and adjoint executable
#cp ../../input/* .
cp ../../build_ad/mitgcmuv_ad .

## remove old files
rm STD*
rm output*
rm costfinal
rm -r PROF
rm *equi*

## set adjoint specific data files to the expected names
cp data.pkg_ad data.pkg
cp data.ctrl_ad data.ctrl
cp data_ad data

mpirun -n 192 ./mitgcmuv_ad > output_ad.txt

rm w2*
