#!/bin/sh
# ------------------------------------------------------------------------------
#
#PBS -A XXX
#PBS -N tpose_optim
#PBS -j oe
#PBS -q main
#PBS -l walltime=00:40:00
#PBS -l select=1:ncpus=128:mpiprocs=1

## load modules (compiler, MPI, etc.)
module --force  purge
module load ncarenv/23.09 intel/2023.2.1 intel-mpi/2021.10.0
module list

cd /glade/derecho/scratch/edavenport/assim/tpose/opti/

#cp /glade/derecho/scratch/edavenport/assim/tpose/sep2012/run_ad/ecco* .
cp /glade/work/edavenport/optim_m1qn3/src/optim.x .

#limit stacksize unlimited
mpirun -n 1 ./optim.x > output_optim.txt

cp ecco_ct* /glade/derecho/scratch/edavenport/assim/tpose/sep2012/run_ad/
