#!/bin/sh
## ------------------------------------------------------------------------------
## need to copy data files for running into desired run folder
## -j oe combines output (o) and error (e) into one file (default behavior separates them)

#PBS -A XXX
#PBS -N tpose_sens_EUC
#PBS -j oe
#PBS -q main
#PBS -l walltime=06:00:00
#PBS -l select=3:ncpus=128:mpiprocs=64

## load modules (compiler, MPI, etc.)
module --force  purge
module load ncarenv/23.09 intel/2023.2.1 intel-mpi/2021.10.0
module list

export TMPDIR=/glade/derecho/scratch/edavenport/temp && mkdir $TMPDIR

cd /glade/derecho/scratch/edavenport/assim/tpose/sens_EUC/run_ad/

## link necessary inputs, which of these need to be linked every time? 
ln -s ../../constraints/* .
ln -s ../../linked_files/* .
ln -s /glade/work/edavenport/ERA5/ERA5* .
ln -s ../../previous_state/* .

## copy data files, adjoint executable, and masks
cp ../../input/* .
cp ../../build_ad/mitgcmuv_ad .
cp /glade/derecho/scratch/edavenport/TPOSE6_Sensitivity/model_setup/EUC_transect/* .
mv maskK.bin sens_maskK
mv maskW.bin sens_maskW
mv maskT.bin sens_maskT
mv maskS.bin sens_maskS

## remove old files
rm STD*
rm output*
rm costfinal
rm -r PROF
rm *equi*

## set adjoint specific data files to the expected names
cp data.pkg_sens data.pkg
cp data.ctrl_ad data.ctrl
cp data_sens data
cp data.ecco_QoI data.ecco

mpirun -n 192 ./mitgcmuv_ad > output.txt

rm w2*
